services:
  frontend:
    build:
      context: ./Batman
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - services-network
    depends_on:
      - backend

  backend:
    build:
      context: ./gotham
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: batcave
      PGPORT: 5432
      PGHOST: db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: batcave
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  db_data:

networks:
  services-network:
    name: services-network
    driver: bridge