services:
  web:
    build:
      context: ./gotham
    ports:
      - "4000:4000"
    volumes:
      - .:/gotham
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
