import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :gothapp, TmanWeb.Endpoint,
       server: true,
       cache_static_manifest: "priv/static/cache_manifest.json",
       show_sensitive_data_on_connection_error: true,
       username: System.get_env("PGUSER"),
       password: System.get_env("PGPASSWORD"),
       database: System.get_env("PGDATABASE"),
       hostname: System.get_env("PGHOST")

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Tman.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
